Fixex IComparable exception
In DescendingMetricSquad:

EXCEPTION: System.ArgumentException: IComparer (or the IComparable methods
it relies upon) did not return zero when Array.Sort called x.
CompareTo(x). x: ''  x's type: 'SquadRoster' The IComparer:
'System.Array+FunctorComparer`1[PRoConEvents.MULTIbalancer+SquadRoster]'.
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32
   index, Int32 length, IComparer`1 comparer)
      at System.Array.Sort[T](T[] array, Int32 index, Int32 length,
      IComparer`1 comparer)
         at System.Collections.Generic.List`1.Sort(Comparison`1
	 comparison)
	    at PRoConEvents.MULTIbalancer.ScramblerLoop()

Because not returning 0 for lhs == rhs.